# Generated by Django 5.0.6 on 2024-06-09 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DONE', 'DONE'), ('INPROGRESS', 'INPROGRESS')], max_length=30)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2024, 6, 9, 15, 31, 41, 966127, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
