# Generated by Django 4.2.7 on 2024-06-10 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
